[theme]
primaryColor = "#1F6F8B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#EEF2F5"
textColor = "#1B2430"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
